adding some updates for dotfiles
adding some updates for alacritty and adding some scripts for xshkd key
maps and update the install scirpts and .zshrc and .xinitrc and update
tmux for some new shourtcuts and adding new patch for dwm and slstatus
and adding some update for slstatus

diff --git a/scripts/bright b/scripts/bright
--- a/scripts/bright
+++ b/scripts/bright
@@ -6,20 +6,29 @@ checkCommand() {
 
 setBrightness() {
   checkCommand brightnessctl
+
   if [ $? -eq 0 ]; then
-    brightnessctl set $1%
-    exit 0
+     if [[ $1 == "up" ]]; then
+        brightnessctl set +15% > /dev/null
+        exit 0
+     elif [[ $1 == "down" ]]; then
+        brightnessctl set 15%- > /dev/null
+        exit 0
+     else
+        brightnessctl set $1%
+        exit 0
+     fi
   else
-    echo -e "=> brightnessctl not found"
-    echo -e "=> starting installation"
-    sudo pacman -S brightnessctl
-    if [ $? -eq 0 ]; then
-      sudo brightnessctl set $1
-      exit 0
-    else
-      echo -e "=> failed to install brightnessctl"
-      exit 1
-    fi
+     echo -e "=> brightnessctl not found"
+     echo -e "=> starting installation"
+     sudo pacman -S brightnessctl
+     if [ $? -eq 0 ]; then
+        sudo brightnessctl set $1
+        exit 0
+     else
+        echo -e "=> failed to install brightnessctl"
+        exit 1
+     fi
   fi
 }
 setBrightness $1
