adding some updates for scripts and notes

diff --git a/scripts/install_scripts/_install_tmp b/scripts/install_scripts/_install_tmp
--- a/scripts/install_scripts/_install_tmp
+++ b/scripts/install_scripts/_install_tmp
@@ -7,17 +7,17 @@ GREEN='\e[32m'
 
 
 install_tmp() {
-  dir="$HOME/.tmux/plugins/tpm"
-  if [ -d "$dir" ]; then
-    echo -e "${GREEN}-- tmp already cloned $dir --${RC}"
-  else
-    git clone https://github.com/tmux-plugins/tpm ~/.tmux/plugins/tpm
-    if [ $? -eq 0 ]; then
-      echo -e "${GREEN}-- cloning tmp sucessfuly -- ${RC}"
+    dir="$HOME/.tmux/plugins/tpm"
+    if [ -d "$dir" ]; then
+        echo -e "${GREEN}-- tmp already cloned $dir --${RC}"
     else
-      echo -e "${RED}** error happend in clone tmp **{RC}"
+        git clone https://github.com/tmux-plugins/tpm ~/.tmux/plugins/tpm
+        if [[ $? == 0 ]]; then
+            echo -e "${GREEN}-- cloning tmp sucessfuly -- ${RC}"
+        else
+            echo -e "${RED}** error happend in clone tmp **{RC}"
+        fi
     fi
-  fi
 }
 
 install_tmp
diff --git a/scripts/install_scripts/install_rust_cargo b/scripts/install_scripts/install_rust_cargo
--- a/scripts/install_scripts/install_rust_cargo
+++ b/scripts/install_scripts/install_rust_cargo
@@ -1,6 +1,19 @@
 #!/usr/bin/env bash
 
-curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh
-source "$HOME/.cargo/env"
+_install() {
+    if _commend_exists cargo; then
+        printf 'commend found cargo'
+        exit 1
+    fi
+    printf "starting install cargo and rust"
+    curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh
+    source "$HOME/.cargo/env"
+    if [[ $? == 0 ]]; then
+        printf "install successfuly rust and cargo"
+    else
+        printf "error happend in install cargo and rust" 
+    fi
+}
+_install
 
 
